### ISSUE TITLE
Closed Stream on successive call after exception

### ISSUE THREAD

**Issue by ghost** [cassandra-rb/cassandra#118]
## Steps to reproduce:
1. Create a client
2. Call any method with a count of 1 trillion (1_000_000_000_000) - this raises a RangeError
3. Call the method again with a count of 1 billion (valid)
   - This causes an IOError: closed stream
4. Call the method above one more time, all is well

I tried this with #count_columns and #get - behavior is the same.
## Example

``` ruby
client = Cassandra.new keyspace
# => <Cassandra:70288410646880, @keyspace="Foo", @schema={}, @servers=["127.0.0.1:9160"]> 

client.count_columns column_family, 'foos'
# => 0 

client.count_columns column_family, 'foos', :count => 1_000_000_000
# => 0 

client.count_columns column_family, 'foos', :count => 1_000_000_000_000

# Raises the following:
# ==========================================
# RangeError: RangeError
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift-0.7.0/lib/thrift/protocol/binary_protocol.rb:95:in `write_i32'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift-0.7.0/lib/thrift/client.rb:35:in `write'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift-0.7.0/lib/thrift/client.rb:35:in `send_message'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/cassandra-0.12.1/lib/../vendor/0.8/gen-rb/cassandra.rb:89:in `send_get_count'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/cassandra-0.12.1/lib/../vendor/0.8/gen-rb/cassandra.rb:84:in `get_count'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:131:in `send'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:131:in `handled_proxy'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:60:in `get_count'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/cassandra-0.12.1/lib/cassandra/protocol.rb:15:in `_count_columns'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:519:in `count_columns'
#   from (irb):22


client.count_columns column_family, 'foos', :count => 1_000_000_000

# Raises the following:
# ==========================================
# IOError: closed stream
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift-0.7.0/lib/thrift/transport/socket.rb:62:in `write'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift-0.7.0/lib/thrift/transport/framed_transport.rb:96:in `flush'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift-0.7.0/lib/thrift/client.rb:41:in `send_message'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/cassandra-0.12.1/lib/../vendor/0.8/gen-rb/cassandra.rb:89:in `send_get_count'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/cassandra-0.12.1/lib/../vendor/0.8/gen-rb/cassandra.rb:84:in `get_count'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:131:in `send'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:131:in `handled_proxy'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/thrift_client-0.7.0/lib/thrift_client/abstract_thrift_client.rb:60:in `get_count'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/cassandra-0.12.1/lib/cassandra/protocol.rb:15:in `_count_columns'
#   from /home/racker/.rvm/gems/ruby-1.8.7-p174@global/gems/cassandra-0.12.1/lib/cassandra/cassandra.rb:519:in `count_columns'
#   from (irb):23

client.count_columns column_family, 'foos', :count => 1_000_000_000
# => 0 
# ^-- Notice nothing raised on successive call
```

**Comment by ghost** [comment]
Any movement on this issue?

**Comment by BaloMueller** [comment]
This bug still exists :-(

**Comment by natemueller** [comment]
Thrift::Client#send_message will catch exceptions writing the message to the server, close the connection and re-raise.  I'm still looking but I'm not sure there's a reliable way to distinguish, at the cassandra layer, between exceptions that close the socket and ones that don't.  There's a built-in assumption that any data passed in will fit in the thrift data types.

The interplay between thrift, thrift-client and cassandra makes this very tricky to fix.  I think the correct thing is for thrift to not close the connection.  If this is a pain point for you I'd file it with that project.
