### ISSUE TITLE
Gem now requires Cassandra 0.6-beta

### ISSUE THREAD

**Issue by mperham** [cassandra-rb/cassandra#17]
batch_mutate is only in Cassandra 0.6.  Since 0.6 hasn't even been generally released yet, I think it would be nice to use the 0.5 API for a while where possible.  Here's the API wiki page so you can verify any other API changes: http://wiki.apache.org/cassandra/API

```
qanat.4.log:Hoptoad: Thrift::ApplicationException: Invalid method name: 'batch_mutate'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/thrift-0.0.810255.1/lib/thrift/client.rb:58:in `handle_exception'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/thrift-0.0.810255.1/lib/thrift/client.rb:46:in `receive_message'
qanat.4.log:/home/onespot/.bundle/ruby/1.9.1/gems/cassandra-0.7.6/vendor/gen-rb/cassandra.rb:219:in `recv_batch_mutate'
qanat.4.log:/home/onespot/.bundle/ruby/1.9.1/gems/cassandra-0.7.6/vendor/gen-rb/cassandra.rb:211:in `batch_mutate'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:60:in `send_rpc'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:156:in `send_rpc'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:56:in `proxy'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:146:in `proxy'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:49:in `handled_proxy'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:142:in `handled_proxy'
qanat.4.log:/home/onespot/.bundle/ruby/1.9.1/gems/thrift_client-0.4.1/lib/thrift_client/abstract_thrift_client.rb:23:in `batch_mutate'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/cassandra-0.7.6/lib/cassandra/protocol.rb:8:in `_mutate'
qanat.4.log-/home/onespot/.bundle/ruby/1.9.1/gems/cassandra-0.7.6/lib/cassandra/cassandra.rb:110:in `insert'
```

**Comment by ryanking** [comment]
We haven't done a gem release since I started working on batch_mutate. I plan on making the next gem release 0.6 only.

**Comment by mperham** [comment]
Ah, ok.  I had pulled the latest changes to test my thrift_client fixes.

**Comment by ryanking** [comment]
so, not a problem?

**Comment by mperham** [comment]
We upgraded to 0.6 also so this is no longer an issue for us.
