### ISSUE TITLE
Always tries to connect to 127.0.0.1:9160

### ISSUE THREAD

**Issue by kmarsh** [cassandra-rb/cassandra#171]
I'm seeing some weird behavior with cassandra-0.17.0 on ruby 1.9.3p194.

When I specify an IP and port to connect to, and try to get a row I get a `ThriftClient::NoServersAvailable: No live servers in [127.0.0.1:9160]` exception:

```
1.9.3p194 :001 > require 'cassandra'
 => true 
1.9.3p194 :002 > client = Cassandra.new('DEMO', '192.168.1.11:9160')
 => #<Cassandra:70101060660780, @keyspace="DEMO", @schema={}, @servers=["192.168.1.11:9160"]> 
1.9.3p194 :003 > client.get(:Users, '1234')
ThriftClient::NoServersAvailable: No live servers in [127.0.0.1:9160].
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.8.2/lib/thrift_client/abstract_thrift_client.rb:136:in `next_live_server'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.8.2/lib/thrift_client/abstract_thrift_client.rb:94:in `connect!'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.8.2/lib/thrift_client/abstract_thrift_client.rb:142:in `handled_proxy'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/thrift_client-0.8.2/lib/thrift_client/abstract_thrift_client.rb:51:in `describe_keyspace'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.17.0/lib/cassandra/cassandra.rb:181:in `schema'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.17.0/lib/cassandra/columns.rb:57:in `column_family_property'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.17.0/lib/cassandra/columns.rb:44:in `column_name_class_for_key'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.17.0/lib/cassandra/columns.rb:12:in `column_name_class'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.17.0/lib/cassandra/helpers.rb:21:in `extract_and_validate_params'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.17.0/lib/cassandra/cassandra.rb:622:in `multi_get'
    from /Users/kmarsh/.rvm/gems/ruby-1.9.3-p194/gems/cassandra-0.17.0/lib/cassandra/cassandra.rb:597:in `get'
    from (irb):3
    from /Users/kmarsh/.rvm/rubies/ruby-1.9.3-p194/bin/irb:16:in `<main>'
```

The node is up and serving requests at that IP/port, as verified with cassandra-cli on the same machine:

```
apache-cassandra-1.1.7$ ./bin/cassandra-cli -h 192.168.1.11
Connected to: "Seek Beta Cluster" on 192.168.1.11/9160
Welcome to Cassandra CLI version 1.1.7

Type 'help;' or '?' for help.
Type 'quit;' or 'exit;' to quit.

[default@unknown] use DEMO;       
Authenticated to keyspace: DEMO
[default@DEMO] get Users[1234];
=> (column=name, value=Kevin, timestamp=1355067890923000)
=> (column=password, value=secret, timestamp=1355067914388000)
Returned 2 results.
Elapsed time: 14 msec(s).
```

I am also able to connect to a node on 127.0.0.1:9160 if one is running.

**Comment by kmarsh** [comment]
So, after a bit of investigation it seems as though this is being caused by `@auto_discover_nodes` being set to true. I disabled this functionality by calling `client.disable_node_auto_discovery!` and it no longer tries to add localhost and only uses servers specified.

I'm don't know enough about Cassandra to say this is a good default behavior or not, so I'll leave it up to the experts.

**Comment by ryanking** [comment]
You need to change your server to bind on a non-loopback address and you'll
be fine.

**Comment by magedmakled** [comment]
@ryanking, what does that mean to bind to a non-loopback address, I have the same problem but not on a localhost but on AWS

**Comment by ryanking** [comment]
Just remember that every host is it's own localhost.

So being on aws doesn't matter.

**Comment by magedmakled** [comment]
Sorry can you elaborate more? Like If I have a node0_ip address on ec2, do I put that IP address before the 127.0.0.1:9160? sorry I'm new to Cassandra
