### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by HParker** [cassandra-rb/cassandra#214]
It seems that the README are rather out of date. for example, naively running the first example fails.

``` ruby
irb(main):003:0> client.insert(:Users, "5", {'screen_name' => "buttonscats"})
```

```
CassandraThrift::InvalidRequestException: CassandraThrift::InvalidRequestException
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/vendor/0.8/gen-rb/cassandra.rb:348:in `recv_describe_ring'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/vendor/0.8/gen-rb/cassandra.rb:338:in `describe_ring'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:165:in `block in handled_proxy'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:146:in `ensure_socket_alignment'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:165:in `handled_proxy'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/thrift_client-0.8.4/lib/thrift_client/abstract_thrift_client.rb:53:in `describe_ring'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/cassandra.rb:1035:in `all_nodes'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/cassandra.rb:1020:in `reconnect!'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/cassandra.rb:1014:in `client'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/cassandra.rb:180:in `schema'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/columns.rb:57:in `column_family_property'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/columns.rb:44:in `column_name_class_for_key'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/columns.rb:12:in `column_name_class'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/helpers.rb:21:in `extract_and_validate_params'
    from /Users/adam/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cassandra-0.23.0/lib/cassandra/cassandra.rb:399:in `insert'
    from (irb):3
    from /Users/adam/.rbenv/versions/2.1.2/bin/irb:11:in `<main>'
```

 It would be great if someone more experienced could update them for new comers like myself.

I think my specific issue is related to #107. It would be nice to know to setup my schema without searching through closed issues.

**Comment by psanford** [comment]
Inexperienced users probably should be using the Datastax [ruby-driver](https://github.com/datastax/ruby-driver) instead of this gem. I've submitted a pull request to clarify the status of this project and point users to the ruby-driver.

**Comment by HParker** [comment]
Thanks @psanford. the link is very helpful.
