### ISSUE TITLE
Cassandra#exists? throws error

### ISSUE THREAD

**Issue by mperham** [cassandra-rb/cassandra#26]
I'm just trying to verify if Cassandra has a particular key in the keyspace.

```
>> require 'cassandra'
>> c = Cassandra.new 'Onespot', 'localhost:9160'
>> c.exists?(:UrlInfo, 'foo')

Thrift::ProtocolException: Required field start is unset!
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/cassandra-0.8.2/lib/../vendor/gen-rb/cassandra_types.rb:304:in `validate'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift-0.2.0.2/lib/thrift/client.rb:35:in `write'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift-0.2.0.2/lib/thrift/client.rb:35:in `send_message'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/cassandra-0.8.2/lib/../vendor/gen-rb/cassandra.rb:92:in `send_multiget_slice'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/cassandra-0.8.2/lib/../vendor/gen-rb/cassandra.rb:87:in `multiget_slice'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in `send'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:64:in `send_rpc'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:161:in `send_rpc'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:60:in `proxy'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:151:in `proxy'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:53:in `handled_proxy'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:147:in `handled_proxy'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/thrift_client-0.4.3/lib/thrift_client/abstract_thrift_client.rb:23:in `multiget_slice'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/cassandra-0.8.2/lib/cassandra/protocol.rb:69:in `_multiget'
from /opt/ruby-enterprise-1.8.7-2009.10/lib/ruby/gems/1.8/gems/cassandra-0.8.2/lib/cassandra/cassandra.rb:216:in `exists?'
```

**Comment by jmhodges** [comment]
fixing exists? when given only a key. closed by e3fefa39e6aa5517ede51d5e3ce98396f56cb554.
