### ISSUE TITLE
Can't insert nil values

### ISSUE THREAD

**Issue by timhaines** [cassandra-rb/cassandra#8]
Have a column family with super columns.  Trying to create columns with tweet ids as the key, and nil as the value.  I get an error on .insert.

"Required field value is unset!"

Exception is raised from the CassandraThrift Column class's validate method 
at Line 42 in vendor/gen-rb/cassandra_types.rb

**Comment by ryanking** [comment]
Can you paste some actual code?

**Comment by timhaines** [comment]
```
>script/console 
Loading development environment (Rails 2.3.5)
>>  @cassandra =  Cassandra.new('Favstar')
=> #<Cassandra:20994830, @keyspace="Favstar", @schema={}, @servers=["127.0.0.1:9160"]>
>> @cassandra.insert(:GroupVectors, "row_key", {"super_column_key" => {20 => nil} })
Thrift::ProtocolException: Required field value is unset!
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/cassandra-0.7.1/lib/../vendor/gen-rb/cassandra_types.rb:42:in `validate'
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/thrift-0.0.810255.1/lib/thrift/client.rb:35:in `write'
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/thrift-0.0.810255.1/lib/thrift/client.rb:35:in `send_message'
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/cassandra-0.7.1/lib/../vendor/gen-rb/cassandra.rb:165:in `send_batch_insert'
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/cassandra-0.7.1/lib/../vendor/gen-rb/cassandra.rb:160:in `batch_insert'
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/thrift_client-0.3.2/lib/thrift_client.rb:125:in `send'
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/thrift_client-0.3.2/lib/thrift_client.rb:125:in `proxy'
    from (eval):1:in `batch_insert'
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/cassandra-0.7.1/lib/cassandra/protocol.rb:8:in `_insert'
    from /opt/ruby-enterprise-1.8.6-20090610/lib/ruby/gems/1.8/gems/cassandra-0.7.1/lib/cassandra/cassandra.rb:109:in `insert'
    from (irb):2
```

**Comment by ryanking** [comment]
thanks. i'll dig into it as soon as I can.

**Comment by ryanking** [comment]
Fixed in http://github.com/fauna/cassandra/commit/a86234a42e602ba9cbfa8708f282277ac7f811da

Please test.
