### ISSUE TITLE
String-based :start parameter to get_range fails

### ISSUE THREAD

**Issue by kyptin** [cassandra-rb/cassandra#81]
Consider this code, which should return the same row twice:

``` ruby
require 'cassandra/0.7'
conn = Cassandra.new(keyspace, '127.0.0.1:9160')
results  = conn.get_range(column_family, :count => 1)
results2 = conn.get_range(column_family, :count => 1,
                          :start => results.first.key)
```

Instead, the code above produces the following error:

```
/home/jeff/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.10.0/lib/cassandra/long.rb:20:in `initialize':
Expected "17.79.18.24:50164" to cast to a Cassandra::Long (invalid bytecount)
Cassandra::Comparable::TypeError)
  from /home/jeff/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.10.0/lib/cassandra/helpers.rb:25:in `new'
  from /home/jeff/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.10.0/lib/cassandra/helpers.rb:25:in `block in extract_and_validate_params'
  from /home/jeff/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.10.0/lib/cassandra/helpers.rb:24:in `each'
  from /home/jeff/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.10.0/lib/cassandra/helpers.rb:24:in `extract_and_validate_params'
  from /home/jeff/.rvm/gems/ruby-1.9.2-p136/gems/cassandra-0.10.0/lib/cassandra/cassandra.rb:235:in `get_range'
  from get_keys.rb:11:in `<main>'
```

Just in case it matters, here are a few details of my environment:
- Cassandra version 0.7.4.
- Cassandra gem version 0.10.0.
- The key in `results.first.key` is `17.79.18.24:50164`.
- The column family schema is as follows:

```
ColumnFamily: SRT
  Columns sorted by: org.apache.cassandra.db.marshal.LongType
  Row cache size / save period: 0.0/0
  Key cache size / save period: 200000.0/14400
  Memtable thresholds: 1.70625/364/1440
  GC grace seconds: 864000
  Compaction min/max thresholds: 4/32
  Read repair chance: 1.0
  Built indexes: []
```

**Comment by rwjblue** [comment]
Closing duplicate issue.
