### ISSUE TITLE
`clear_keyspace!' call seems to crash

### ISSUE THREAD

**Issue by rb2k** [cassandra-rb/cassandra#91]
The clean_keyspace! call seems to crash if I don't have a long enough pause before/after it (current git version, cassandra 0.8 final)

```
/Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift-0.6.0/lib/thrift/transport/socket.rb:109:in `read': CassandraThrift::Cassandra::Client::TransportException
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift-0.6.0/lib/thrift/transport/base_transport.rb:52:in `read_all'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift-0.6.0/lib/thrift/transport/framed_transport.rb:78:in `read_frame'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift-0.6.0/lib/thrift/transport/framed_transport.rb:49:in `read'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift-0.6.0/lib/thrift/transport/base_transport.rb:52:in `read_all'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift-0.6.0/lib/thrift/protocol/binary_protocol.rb:186:in `read_i32'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift-0.6.0/lib/thrift/protocol/binary_protocol.rb:111:in `read_message_begin'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift-0.6.0/lib/thrift/client.rb:45:in `receive_message'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/cassandra-0.11.1/vendor/0.8/gen-rb/cassandra.rb:268:in `recv_truncate'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/cassandra-0.11.1/vendor/0.8/gen-rb/cassandra.rb:260:in `truncate'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:116:in `handled_proxy'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:58:in `truncate'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:229:in `truncate!'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:244:in `block in clear_keyspace!'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:244:in `each'
from /Users/mseeger/.rvm/gems/ruby-1.9.2-p180/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:244:in `clear_keyspace!'
```

**Comment by kindkid** [comment]
I saw this error too when calling the truncate! method.

I fixed it by adding some options when I called Cassandra.new...

```
cass = Cassandra.new(keyspace, servers, :retries => 2, :timeout => 3, :connect_timeout => 3)
```

The one that made the difference was the :connect_timeout.

**Comment by rwjblue** [comment]
Does anyone have any objection to making the default :connect_timeout something like 0.1?

That seems to resolve these errors in the test suite using my local single instance cluster, but I am not able to test on a multi-machine setup.

**Comment by Ghassan** [comment]
[1] is the :connect_timeout time measured in seconds or milliseconds?
[2] if the :connect_timeout value is the amount of time in which the connection is a live for the client and after which the client will disconnect then wouldn't it make more sense to have this parameter mandatory instead of optional?

so a typical client would start by:

client = Cassandra.new(keyspace_name , servers_ip_:_port,  :connect_timeout => 3)

this way the programmer is aware of the lifetime of the connection which is <= lifetime of the client.

[3] also, how do I have a connection that lasts for ever? :connect_timeout=>"infinity"
[4] if we were to have an "infinity" connection, then what would happen to the actual connection when the client is closed? how does thrift handle that? Does it get recycled?
[5] how does the :connect_timeout stack up in relation to other options, I really do not know. I see :timeout and :retries ?
[6] how is the exception handling is handled in this scenario: the connection lifetime <= client's lifetime?

can I help in documenting the gem?

Thanks a lot.

**Comment by rwjblue** [comment]
[1] - :connect_timeout is measured in seconds with a default of 0.1.

[2] - The :connect_timeout parameter is only the timeout to actually initiate the connection to the Cassandra server.  Once connected the :timeout parameter is used (which defaults to 1 second) for future IO activities with the server.  Again, to reiterate, neither of these parameters indicate a lifetime.  The connection to a given server can theoretically be open forever, but if it takes longer than 0.1 seconds to open the connection or longer than 1 second for reads/writes then a timeout error will be raised.

[5] - The :connect_timeout is really only a factor if it takes longer than 0.1 second to connect.  On a localhost or dedicated high-speed LAN this should be more than enough time.  IMHO, the real benefit of a longer :connect_timeout is when using servers that are being connected to over a relatively slow (1.54Mbps - 5Mbps) connection.

Hopefully, I have answered most of the questions...

**Comment by ivmaykov** [comment]
I've seen this failure in a local integration test that spins up a cass 0.8 cluster, so the default 0.1 second connect timeout seems to occasionally be too low even for some local setups. +1 for bumping the connect timeout default to 1 second.

**Comment by rwjblue** [comment]
Would it be possible for you to run your integration tests with variable :connect_timeout values (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, and 1.0) and see where the issues tail off?  I do not have any errors when running locally or remotely with the current default of 0.1 so I can test for errors locally.

I do not mind setting the default timeout value to 1.0, but I just want to make sure that we don't set it too high or too low.

**Comment by ivmaykov** [comment]
It seems to fail occasionally even with a 5 second :connect_timeout. I will do more testing today to try and nail it down.

**Comment by natemueller** [comment]
These ops require a flush on the server and can take a while.  Since it depends on things like disk speed and pending memtable changes I don't think we'll be able to pick a default timeout that handles them and doesn't wait too long for normal queries.  I recommend using a separate connection with a high timeout and no retries for schema changes and truncates.
