### ISSUE TITLE
Thrift exceptions in JRuby

### ISSUE THREAD

**Issue by iconara** [cassandra-rb/cassandra#93]
The readme doesn't mention JRuby support, so perhaps this is not a bug as such. This is what happens when I try to connect to Cassandra in JRuby 1.6.2

```
ruby-1.6.2 :001 > require 'cassandra/0.8'
Unable to load thrift_native extension. Defaulting to pure Ruby libraries.
  => true
jruby-1.6.2 :002 > c = Cassandra.new('TestSpace')
  => #<Cassandra:2162, @keyspace="TestSpace", @schema={}, @servers=["127.0.0.1:7000"]> 
jruby-1.6.2 :003 > c.keyspaces
CassandraThrift::Cassandra::Client::TransportException: CassandraThrift::Cassandra::Client::TransportException
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/thrift-0.6.0/lib/thrift/transport/socket.rb:53:in `open'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/thrift-0.6.0/lib/thrift/transport/framed_transport.rb:37:in `open'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/thrift_client-0.6.2/lib/thrift_client/connection/socket.rb:11:in `connect!'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:83:in `connect!'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:111:in `handled_proxy'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/thrift_client-0.6.2/lib/thrift_client/abstract_thrift_client.rb:58:in `describe_ring'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:1024:in `all_nodes'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:1016:in `reconnect!'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:1009:in `client'
  from /Users/theo/.rvm/gems/jruby-1.6.2@rich_collection/gems/cassandra-0.11.1/lib/cassandra/cassandra.rb:148:in `keyspaces'
  from (irb):3:in `evaluate'
  from org/jruby/RubyKernel.java:1093:in `eval'
  from org/jruby/RubyKernel.java:1419:in `loop'
  from org/jruby/RubyKernel.java:1205:in `catch'
  from org/jruby/RubyKernel.java:1205:in `catch'
  from /Users/theo/.rvm/rubies/jruby-1.6.2/bin/irb:17:in `(root)'
```

If JRuby is unsupported, could you give me any tips on how to work with Cassandra in JRuby? Using the Java API is of course possible, but it looks so much more verbose than this gem.

**Comment by rykov** [comment]
This is a "bug" with the thrift gem, not cassandra.  The method _open_ in thrift/transport/socket.rb assumes that IO.select will block while a connection is pending and will return nil if a connection fails.  This is the behavior in MRI.  In jRuby, the IO.select call doesn't block if the connections is still pending and returns nil (see [JRUBY-5165](http://jira.codehaus.org/browse/JRUBY-5165)).  I had to use a patched version of the Thrift gem:

``` ruby
           @handle.connect_nonblock(sockaddr)
         rescue Errno::EINPROGRESS
-          unless IO.select(nil, [ @handle ], nil, @timeout)
-            raise TransportException.new(TransportException::NOT_OPEN, "Connection timeout to #{@desc}")
-          end
+          resp = IO.select(nil, [ @handle ], nil, @timeout)
           begin
             @handle.connect_nonblock(sockaddr)
```

**Comment by iconara** [comment]
Thanks a lot, that seems to work.
